//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Information_vo_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Information_vo_()
        {
            this.address_code_volunteer_ = new HashSet<address_code_volunteer_>();
            this.cars = new HashSet<cars>();
            this.langueges_volunteer_code_ = new HashSet<langueges_volunteer_code_>();
            this.license = new HashSet<license>();
            this.Military_Service = new HashSet<Military_Service>();
            this.weapons_license = new HashSet<weapons_license>();
        }
    
        public int code_volunteer { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public int id { get; set; }
        public int code_title { get; set; }
        public System.DateTime birth_date { get; set; }
        public int code_gender { get; set; }
        public int phone_number { get; set; }
        public int phone_type { get; set; }
        public string address { get; set; }
        public int status { get; set; }
        public string mail_address { get; set; }
        public int code_Languages { get; set; }
        public string Level_of_know { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_code_volunteer_> address_code_volunteer_ { get; set; }
        public virtual availability_volunteer_ availability_volunteer_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cars> cars { get; set; }
        public virtual gender gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<langueges_volunteer_code_> langueges_volunteer_code_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<license> license { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Military_Service> Military_Service { get; set; }
        public virtual personal_status personal_status { get; set; }
        public virtual Phone_type Phone_type1 { get; set; }
        public virtual training training { get; set; }
        public virtual tytel tytel { get; set; }
        public virtual Volunteer_domain Volunteer_domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<weapons_license> weapons_license { get; set; }
    }
}
