//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Information_Assisted_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal_Information_Assisted_()
        {
            this.address_code_assisted_ = new HashSet<address_code_assisted_>();
            this.assisted_domain = new HashSet<assisted_domain>();
            this.langueges_assisted_code_ = new HashSet<langueges_assisted_code_>();
        }
    
        public int code_Assisted { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public int code_tytel { get; set; }
        public string code_gender { get; set; }
        public int phone_number { get; set; }
        public string phone_type { get; set; }
        public string adres { get; set; }
        public string personal_status { get; set; }
        public int code_languages { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_code_assisted_> address_code_assisted_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assisted_domain> assisted_domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<langueges_assisted_code_> langueges_assisted_code_ { get; set; }
        public virtual Requests_for_help Requests_for_help { get; set; }
    }
}
