//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities : DbContext
    {
        public projectEntities()
            : base("name=projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<address_code_volunteer_> address_code_volunteer_ { get; set; }
        public virtual DbSet<address_code_assisted_> address_code_assisted_ { get; set; }
        public virtual DbSet<assisted_domain> assisted_domain { get; set; }
        public virtual DbSet<availability_volunteer_> availability_volunteer_ { get; set; }
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<city> city { get; set; }
        public virtual DbSet<days_code_> days_code_ { get; set; }
        public virtual DbSet<domain> domain { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<langueges_assisted_code_> langueges_assisted_code_ { get; set; }
        public virtual DbSet<langueges_volunteer_code_> langueges_volunteer_code_ { get; set; }
        public virtual DbSet<license> license { get; set; }
        public virtual DbSet<License_type_code_> License_type_code_ { get; set; }
        public virtual DbSet<Military_Service> Military_Service { get; set; }
        public virtual DbSet<Personal_Information_Assisted_> Personal_Information_Assisted_ { get; set; }
        public virtual DbSet<Personal_Information_vo_> Personal_Information_vo_ { get; set; }
        public virtual DbSet<personal_status> personal_status { get; set; }
        public virtual DbSet<Phone_type> Phone_type { get; set; }
        public virtual DbSet<Requests_for_help> Requests_for_help { get; set; }
        public virtual DbSet<Service_code_> Service_code_ { get; set; }
        public virtual DbSet<shifts_code_> shifts_code_ { get; set; }
        public virtual DbSet<training> training { get; set; }
        public virtual DbSet<training_code_> training_code_ { get; set; }
        public virtual DbSet<type_cars> type_cars { get; set; }
        public virtual DbSet<tytel> tytel { get; set; }
        public virtual DbSet<Volunteer_domain> Volunteer_domain { get; set; }
        public virtual DbSet<volunteering> volunteering { get; set; }
        public virtual DbSet<weapons_license> weapons_license { get; set; }
        public virtual DbSet<Weapons_license_code_> Weapons_license_code_ { get; set; }
    }
}
