//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests_for_help
    {
        public int code_Assisted { get; set; }
        public int code_volunteering { get; set; }
        public System.DateTime date { get; set; }
        public int code_shifts { get; set; }
        public string day { get; set; }
        public string Urgency_level { get; set; }
        public string tenure { get; set; }
    
        public virtual Personal_Information_Assisted_ Personal_Information_Assisted_ { get; set; }
        public virtual shifts_code_ shifts_code_ { get; set; }
        public virtual volunteering volunteering { get; set; }
    }
}
