//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class training
    {
        public int code_volunteer { get; set; }
        public int code_training { get; set; }
        public string rank { get; set; }
    
        public virtual Personal_Information_vo_ Personal_Information_vo_ { get; set; }
        public virtual training_code_ training_code_ { get; set; }
    }
}
