//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapons_license_code_
    {
        public int code_Weapons_license { get; set; }
        public string name_Weapons_license { get; set; }
    
        public virtual weapons_license weapons_license { get; set; }
    }
}
